<?php
session_start();
$errors = $_SESSION['errors'] ?? [];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Local Art Gallery - Artists</title>
    <!-- Link to your CSS files -->
    <link rel="stylesheet" href="../CSS/artists.css">
    <link rel="stylesheet" href="../CSS/navbar.css">
</head>
<body>
    <!-- Conditionally add an unshown element if the user is logged in -->
    <?php if (isset($_SESSION['user_id'])): ?>
        <span id="userLoggedIn" style="display: none;"></span>
    <?php endif; ?>

    <div class="content">
        <nav id="navbar">
            <!-- Navbar generated by JavaScript -->
        </nav>

        <header>
            <h1>Artists</h1>
        </header>

        <main id="content">
            <section id="featured-artists">
                <h2>Featured Artists</h2>
                <!-- Artist for Impressionist Icons Exhibition -->
                <article class="artist-item">
                    <h3>Emma Lathrop</h3>
                    <p>
                        Emma Lathrop is a contemporary artist whose vibrant work breathes new life into the 
                        Impressionist tradition. Drawing inspiration from nature and her travels, Lathrop's 
                        canvases are an explosion of color and emotion. Her recent series "Whispers of the Meadow" 
                        has been critically acclaimed for its innovative brush techniques and captivating light play.
                        <b><em>These are all made up</em></b>
                    </p>
                </article>

                <!-- Artist for Modern Marvels Exhibition -->
                <article class="artist-item">
                    <h3>Alex Zhou</h3>
                    <p>
                        Alex Zhou's artistic expression is found in the intersection of technology and art. 
                        His installations invite viewers to interact with digital landscapes, creating a dialogue 
                        between the virtual world and physical experience. Zhou's work in the "Modern Marvels" 
                        exhibition challenges our perceptions of reality and asks poignant questions about the future of humanity.
                    </p>
                </article>

                <!-- Artist for Avant-Garde Expressions Exhibition -->
                <article class="artist-item">
                    <h3>Sofía Herrera</h3>
                    <p>
                        Sofía Herrera is an avant-garde sculptor whose materials of choice range from reclaimed 
                        metals to organic glass. Her sculptures are not only visually stunning but also commentary 
                        on environmental conservation. Herrera's "Reflections of the Deep," featured in the 
                        "Avant-Garde Expressions" exhibition, earned her the prestigious Sculptor of the Year award.
                    </p>
                </article>
            </section>
        </main>

    </div>
    <footer>
        <p>&copy; 2023 Local Art Gallery</p>
    </footer>

    <script src="../Javascript/navbar.js"></script> <!-- Link to your JavaScript file for the navbar -->
</body>
</html>